name: Composite Demo

on:
  push:
  workflow_dispatch:

jobs:
  utiliser-action-composite:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Initialiser le projet
        uses: ./.github/actions/setup-project
        with:
          node-version: '20'
