name: Reusable Test

on:
  workflow_call:
    inputs:
      node-version:
        description: Version de Node.js a utiliser
        required: false
        default: '20'
        type: string
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Installer les dependances
        run: npm ci

      - name: Executer les tests
        run: npm test
